- name: Install and Start APISIX on MacBook Pro
  hosts: all
  become: yes
  tasks:
    - name: 确保 Docker 正在运行
      shell: systemctl start docker || open -a Docker
      ignore_errors: yes

    - name: 拉取 APISIX Docker 镜像
      shell: docker pull apache/apisix:3.11.0

    - name: 确保 APISIX 容器未运行
      shell: docker rm -f apisix || true

    - name: 运行 APISIX 容器
      shell: |
        docker run -d --name apisix \
          -p 9080:9080 -p 9443:9443 \
          apache/apisix:3.11.0

    - name: 验证 APISIX 是否正常运行
      shell: docker ps | grep apisix
      register: apisix_status
      changed_when: false

    - name: 显示 APISIX 运行状态
      debug:
        msg: "{{ apisix_status.stdout }}"
