- name: Deploy Apache APISIX on MacBook Pro
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Ensure Docker is running
      shell: |
        if ! pgrep -x "Docker" > /dev/null; then
          open --background -a Docker
          sleep 10
        fi
      args:
        executable: /bin/bash

    - name: Clone APISIX Docker repo
      git:
        repo: 'https://github.com/apache/apisix-docker.git'
        dest: '/tmp/apisix-docker'
        update: yes

    - name: Start APISIX using Docker Compose
      shell: |
        cd /tmp/apisix-docker/example
        /usr/local/bin/docker-compose up -d
      args:
        executable: /bin/bash

    - name: Check if APISIX is running
      uri:
        url: "http://127.0.0.1:9080"
        method: GET
        status_code: 404
      register: apisix_status

    - name: Show APISIX status
      debug:
        msg: "{{ apisix_status }}"
