- name: Install Apache APISIX on Kubernetes
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Install Helm if not present
      shell: |
        if ! command -v /tmp/bin/helm &> /dev/null; then
          rm -rf helm-v3.17.1-linux-amd64.tar.gz linux-amd64
          curl -LO https://get.helm.sh/helm-v3.17.1-linux-amd64.tar.gz
          tar -zxvf helm-v3.17.1-linux-amd64.tar.gz
          mkdir -p /tmp/bin
          mv linux-amd64/helm /tmp/bin/helm
          chmod +x /tmp/bin/helm
          rm -rf linux-amd64 helm-v3.17.1-linux-amd64.tar.gz
        fi
      args:
        executable: /bin/bash

    - name: Verify Helm installation
      command: /tmp/bin/helm version
      register: helm_version
      changed_when: false

    - name: Show Helm version
      debug:
        msg: "{{ helm_version.stdout }}"

    - name: Add APISIX Helm repo
      command: /tmp/bin/helm repo add apisix https://charts.apiseven.com
      changed_when: false

    - name: Update Helm repo
      command: /tmp/bin/helm repo update
      changed_when: false

    - name: Deploy APISIX using Helm
      command: /tmp/bin/helm install apisix apisix/apisix --namespace apisix --create-namespace
      register: helm_output

    - name: Display Helm install output
      debug:
        msg: "{{ helm_output.stdout }}"
