- name: Install and Start APISIX on MacBook Pro
  hosts: all
  become: yes
  tasks:
    - name: 确保 Docker 正在运行
      shell: systemctl start docker || open -a Docker
      ignore_errors: yes

    - name: 拉取最新的 APISIX Docker 镜像
      docker_image:
        name: apache/apisix:3.11.0
        source: pull

    - name: 确保 APISIX 容器未运行
      docker_container:
        name: apisix
        state: absent

    - name: 运行 APISIX 容器
      docker_container:
        name: apisix
        image: apache/apisix:3.11.0
        state: started
        ports:
          - "9080:9080"
          - "9443:9443"
        restart_policy: always

    - name: 验证 APISIX 是否正常运行
      shell: docker ps | grep apisix
      register: apisix_status
      changed_when: false

    - name: 显示 APISIX 状态
      debug:
        msg: "{{ apisix_status.stdout }}"
